### PR TITLE
8.x 1.x

### PR DESCRIPTION
**Pull request by kimpepper**
Initial Drupal 8 port

### CODE REVIEW

**Comment by rcaracaus** [comment]
screen shot 2014-04-30 at 4 16 35 pm

Get this when I go to admin page.

**Comment by rcaracaus** [comment]
Module also no appearing on configuration page. > /admin/config/

**Comment by rcaracaus** [comment]
I can confirm the module works. Tested it with two separate domains via XMLHttpRequest.

**Comment by kimpepper** [comment]
@rcaracaus Are you saying the errors aren't appearing for you anymore? I tried to reproduce on the latest 8.x branch of core, and didn't get any errors.

**Comment by ericduran** [comment]
D8 would be a good place to not bring in the same giant textbox as before.

The proper config should be two seperate textfield, one for the path and another for the domain and you should be able to add more via ajax. Nice and simple this would also get rid of all the weird things that need to happen on the submit.

At least that's my thoughts. Any other opinions?

**Comment by fubhy** [comment]
Yes I agree. I've in fact started working on this...

**Comment by kporras07** [comment]
Hey there!
@fubhy, @kimpepper, @andypost, @ericduran, @rcaracaus, @justafish any news on this? I'd like to get involved and help.
This module is really useful

**Comment by jeqq** [comment]
@justafish Could you merge this and push to drupal.org? I think it's the time to have the Drupal 8 version of this module on d.o. Thank you. 

More info: https://www.drupal.org/node/2636964

**Comment by justafish** [comment]
done - thanks so much everyone! https://www.drupal.org/project/cors

**Pull request closed without merging**
